.TH PKGNAME 1 "2026-07-03" "Heirloom Darwin port" "Package Administration"
.SH NAME
pkgname \- extract the package name from a package instance
.SH SYNOPSIS
.B pkgname
.I "pkg-instance"
.SH DESCRIPTION
.B pkgname
prints the plain package name for the given package instance
(either an install-database key or a package on disk).
.SH HEIRLOOM DARWIN PORT
Supports the shared modality flags. See
.BR heirloom-modality (7).
.SH SEE ALSO
.BR pkginfo (1),
.BR pkgadd (1M).
